CREATE TABLE IF NOT EXISTS ow_zentide_source_application (
  application_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  topic_id BIGINT UNSIGNED NOT NULL,
  applicant_id VARCHAR(10) NOT NULL,
  source_name VARCHAR(200) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  canonical_url VARCHAR(2048) NOT NULL,
  canonical_url_hash CHAR(64) NOT NULL,
  trust_tier VARCHAR(24) NOT NULL DEFAULT 'COMMUNITY',
  status VARCHAR(24) NOT NULL DEFAULT 'SUBMITTED',
  review_note VARCHAR(1000) NULL,
  reviewer_account VARCHAR(100) NULL,
  source_id BIGINT UNSIGNED NULL,
  trial_result_json JSON NULL,
  trialed_at DATETIME(3) NULL,
  reviewed_at DATETIME(3) NULL,
  activated_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY(application_id),
  KEY idx_zentide_source_application_queue(status,created_at),
  KEY idx_zentide_source_application_applicant(applicant_id,created_at),
  KEY idx_zentide_source_application_url(canonical_url_hash),
  CONSTRAINT fk_zentide_source_application_topic FOREIGN KEY(topic_id) REFERENCES ow_zentide_topic(topic_id) ON DELETE CASCADE,
  CONSTRAINT fk_zentide_source_application_user FOREIGN KEY(applicant_id) REFERENCES user_info(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_zentide_source_application_source FOREIGN KEY(source_id) REFERENCES ow_zentide_source(source_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ow_zentide_source_application_review (
  review_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  application_id BIGINT UNSIGNED NOT NULL,
  actor_type VARCHAR(24) NOT NULL,
  actor_id VARCHAR(100) NULL,
  action VARCHAR(40) NOT NULL,
  note VARCHAR(1000) NULL,
  detail_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY(review_id),
  KEY idx_zentide_source_application_review(application_id,created_at),
  CONSTRAINT fk_zentide_source_application_review_application FOREIGN KEY(application_id) REFERENCES ow_zentide_source_application(application_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
