CREATE TABLE IF NOT EXISTS ow_job (
    job_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id BIGINT UNSIGNED NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    normalized_key VARCHAR(255) NOT NULL,
    external_job_id VARCHAR(255) NULL,
    title VARCHAR(300) NOT NULL,
    normalized_title VARCHAR(300) NOT NULL,
    primary_city VARCHAR(100) NULL,
    source_url VARCHAR(2048) NOT NULL,
    source_url_hash BINARY(32) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'DISCOVERED',
    first_found_at DATETIME(3) NOT NULL,
    last_confirmed_at DATETIME(3) NOT NULL,
    suspected_closed_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    reopened_at DATETIME(3) NULL,
    consecutive_missing_count INT UNSIGNED NOT NULL DEFAULT 0,
    merge_confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
    current_version_no INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    lock_version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (job_id),
    UNIQUE KEY uk_job_source_normalized_key (source_id, normalized_key),
    KEY idx_job_company_status_updated (company_id, status, updated_at),
    KEY idx_job_source_status (source_id, status),
    KEY idx_job_title_city_status (normalized_title, primary_city, status),
    KEY idx_job_url_hash (source_url_hash),
    CONSTRAINT fk_job_company FOREIGN KEY (company_id) REFERENCES ow_company (company_id) ON DELETE RESTRICT,
    CONSTRAINT fk_job_source FOREIGN KEY (source_id) REFERENCES ow_recruitment_source (source_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ow_job_version (
    job_version_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id BIGINT UNSIGNED NOT NULL,
    version_no INT UNSIGNED NOT NULL,
    snapshot_id BIGINT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    title VARCHAR(300) NOT NULL,
    department VARCHAR(200) NULL,
    cities JSON NULL,
    employment_type VARCHAR(32) NULL,
    recruitment_type VARCHAR(32) NULL,
    education VARCHAR(64) NULL,
    min_experience_years DECIMAL(4,1) NULL,
    max_experience_years DECIMAL(4,1) NULL,
    skills JSON NULL,
    salary_min DECIMAL(12,2) NULL,
    salary_max DECIMAL(12,2) NULL,
    salary_currency CHAR(3) NULL,
    salary_period VARCHAR(20) NULL,
    description MEDIUMTEXT NULL,
    requirements MEDIUMTEXT NULL,
    raw_data JSON NULL,
    published_at DATETIME(3) NULL,
    captured_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (job_version_id),
    UNIQUE KEY uk_job_version_no (job_id, version_no),
    UNIQUE KEY uk_job_version_hash (job_id, content_hash),
    KEY idx_job_version_snapshot (snapshot_id),
    CONSTRAINT fk_job_version_job FOREIGN KEY (job_id) REFERENCES ow_job (job_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_version_snapshot FOREIGN KEY (snapshot_id) REFERENCES ow_page_snapshot (snapshot_id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ow_job_presence_record (
    presence_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    attempt_id BIGINT UNSIGNED NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    presence_status VARCHAR(20) NOT NULL,
    source_healthy TINYINT(1) NOT NULL,
    evidence_snapshot_id BIGINT UNSIGNED NULL,
    recorded_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (presence_id),
    UNIQUE KEY uk_job_presence_attempt_job (attempt_id, job_id),
    KEY idx_job_presence_job_recorded (job_id, recorded_at),
    CONSTRAINT fk_job_presence_attempt FOREIGN KEY (attempt_id) REFERENCES ow_crawl_attempt (attempt_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_presence_job FOREIGN KEY (job_id) REFERENCES ow_job (job_id) ON DELETE CASCADE,
    CONSTRAINT fk_job_presence_snapshot FOREIGN KEY (evidence_snapshot_id) REFERENCES ow_page_snapshot (snapshot_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ow_change_event (
    change_event_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_key BINARY(32) NOT NULL,
    job_id BIGINT UNSIGNED NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    before_version_id BIGINT UNSIGNED NULL,
    after_version_id BIGINT UNSIGNED NULL,
    evidence_snapshot_id BIGINT UNSIGNED NULL,
    field_diff JSON NULL,
    importance VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    detected_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    processed_at DATETIME(3) NULL,
    PRIMARY KEY (change_event_id),
    UNIQUE KEY uk_change_event_key (event_key),
    KEY idx_change_event_job_detected (job_id, detected_at),
    KEY idx_change_event_status_importance (status, importance, detected_at),
    KEY idx_change_event_source_detected (source_id, detected_at),
    CONSTRAINT fk_change_event_job FOREIGN KEY (job_id) REFERENCES ow_job (job_id) ON DELETE CASCADE,
    CONSTRAINT fk_change_event_source FOREIGN KEY (source_id) REFERENCES ow_recruitment_source (source_id) ON DELETE RESTRICT,
    CONSTRAINT fk_change_event_before_version FOREIGN KEY (before_version_id) REFERENCES ow_job_version (job_version_id) ON DELETE SET NULL,
    CONSTRAINT fk_change_event_after_version FOREIGN KEY (after_version_id) REFERENCES ow_job_version (job_version_id) ON DELETE SET NULL,
    CONSTRAINT fk_change_event_snapshot FOREIGN KEY (evidence_snapshot_id) REFERENCES ow_page_snapshot (snapshot_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ow_platform_metadata (metadata_key, metadata_value)
VALUES ('platform_phase', 'scheduled-crawl-and-jobs')
ON DUPLICATE KEY UPDATE metadata_value = VALUES(metadata_value);
