package com.zentide.service;
import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import com.zentide.mapper.ZentideGovernanceMapper; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.util.*;
/**
 * 治理数据控制面。Spring Boot 是规则、审核结果和反馈的唯一持久化入口；
 * Python Agent 只负责读取快照、执行分析并通过内部接口回传结果。
 */
@Service public class ZentideGovernanceControlPlaneService {
 private final ZentideGovernanceMapper mapper; private final ObjectMapper json=new ObjectMapper();
 public ZentideGovernanceControlPlaneService(ZentideGovernanceMapper mapper){this.mapper=mapper;}
 public List<Map<String,Object>> rules(Long scene){List<Map<String,Object>> out=new ArrayList<>(); for(Map<String,Object> source:mapper.listRules(scene)){Map<String,Object> row=new LinkedHashMap<>(source); try{row.put("keywords",json.readValue(String.valueOf(row.remove("keywords_json")),new TypeReference<List<String>>(){}));}catch(Exception e){row.put("keywords",List.of());}out.add(row);}return out;}
 public List<Map<String,Object>> allRules(Long scene){List<Map<String,Object>> out=new ArrayList<>(); for(Map<String,Object> source:mapper.listAllRules(scene)){Map<String,Object> row=new LinkedHashMap<>(source); try{row.put("keywords",json.readValue(String.valueOf(row.remove("keywords_json")),new TypeReference<List<String>>(){}));}catch(Exception e){row.put("keywords",List.of());}out.add(row);}return out;}
 public Map<String,Object> saveRule(Map<String,Object> p){try{mapper.insertRule(0L,String.valueOf(p.get("violation_type")),String.valueOf(p.get("rule_description")),json.writeValueAsString(p.getOrDefault("keywords",List.of())),String.valueOf(p.get("severity")));return Map.of("saved",true);}catch(Exception e){throw new IllegalArgumentException("治理规则保存失败",e);}}
 public Map<String,Object> updateRule(Long id, Map<String,Object> p){try{Object enabledValue=p.get("enabled"); boolean enabled=Boolean.TRUE.equals(enabledValue)||"1".equals(String.valueOf(enabledValue))||"true".equalsIgnoreCase(String.valueOf(enabledValue)); int updated=mapper.updateRule(id,String.valueOf(p.get("violation_type")),String.valueOf(p.getOrDefault("rule_description", "")),json.writeValueAsString(p.getOrDefault("keywords",List.of())),String.valueOf(p.get("severity")),enabled);if(updated!=1)throw new IllegalArgumentException("治理规则不存在");return Map.of("saved",true,"enabled",enabled);}catch(Exception e){throw new IllegalArgumentException("治理规则更新失败",e);}}
 public Map<String,Object> deleteRule(Long id){try{if(mapper.deleteRule(id)!=1)throw new IllegalArgumentException("治理规则不存在");return Map.of("deleted",true);}catch(Exception e){throw new IllegalArgumentException("治理规则删除失败",e);}}
 public void saveResult(Map<String,Object> p){try{mapper.insertResult(String.valueOf(p.get("result_id")),((Number)p.get("content_id")).longValue(),((Number)p.get("scene_id")).longValue(),String.valueOf(p.getOrDefault("risk_level","low")),String.valueOf(p.getOrDefault("suggested_action","allow")),new BigDecimal(String.valueOf(p.getOrDefault("confidence",0))),json.writeValueAsString(p));}catch(Exception e){throw new IllegalArgumentException("治理结果保存失败",e);}}
 public void saveFeedback(Map<String,Object> p,String reviewer){Map<String,Object> data=new LinkedHashMap<>(p);data.put("reviewer_id",reviewer);try{data.put("corrected_violation_types",json.writeValueAsString(p.get("corrected_violation_types")));mapper.insertFeedback(data);}catch(Exception e){throw new IllegalArgumentException("治理反馈保存失败",e);}}
 public List<Map<String,Object>> pendingResults(){List<Map<String,Object>> out=new ArrayList<>();for(Map<String,Object> row:mapper.listPendingResults(300)){try{out.add(json.readValue(String.valueOf(row.get("payload_json")),new TypeReference<Map<String,Object>>(){}));}catch(Exception ignored){}}return out;}
}
