package com.zentide.agent;

public enum AgentStopReason {
    GOAL_COMPLETED,
    NO_NEW_INFORMATION,
    INSUFFICIENT_EVIDENCE,
    UNRESOLVED_CONFLICT,
    WAITING_HUMAN_REVIEW,
    BUDGET_EXHAUSTED,
    TIMEOUT,
    USER_CANCELLED,
    POLICY_BLOCKED,
    INVALID_MODEL_OUTPUT,
    PROVIDER_ERROR
}
